spring:
  profiles:
    active: 'dev'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
---
spring:
  profiles: prod
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/prod_db
      username: postgres
      password: 1234